//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateMe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DateMe.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string ButtonLearnMore {
            get {
                return ResourceManager.GetString("ButtonLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string FirstColumnHeader {
            get {
                return ResourceManager.GetString("FirstColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now and meet people from all over the world..
        /// </summary>
        public static string FirstColumnText {
            get {
                return ResourceManager.GetString("FirstColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string Jumbotron_Button {
            get {
                return ResourceManager.GetString("Jumbotron_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Jumbotron_Greeting {
            get {
                return ResourceManager.GetString("Jumbotron_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateMe is the world&apos;s leading venue for singles looking to pork oh so hard.
        /// </summary>
        public static string Jumbotron_Text {
            get {
                return ResourceManager.GetString("Jumbotron_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of our members.
        /// </summary>
        public static string MemberRoll {
            get {
                return ResourceManager.GetString("MemberRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique profile matching.
        /// </summary>
        public static string SecondColumnHeader {
            get {
                return ResourceManager.GetString("SecondColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare your preferences using our Super-Match och find your perfect match.
        /// </summary>
        public static string SecondColumnText {
            get {
                return ResourceManager.GetString("SecondColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateMe Premium - Soon available.
        /// </summary>
        public static string ThirdColumnHeader {
            get {
                return ResourceManager.GetString("ThirdColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Premium you can try our latest features before anyone else!.
        /// </summary>
        public static string ThirdColumnText {
            get {
                return ResourceManager.GetString("ThirdColumnText", resourceCulture);
            }
        }
    }
}
